### PR TITLE
Fix local download

### PR DESCRIPTION
**Pull request by defoltbmd**
Apply nice-vladi's changes
Revert and refactor percent displaying
Add hint to readme

### CODE REVIEW

**Comment by HaCk3Dq** [comment]
This branch has conflicts that must be resolved. :)

**Comment by defoltbmd** [comment]
@HaCk3Dq так во втором коммите зарезолвил (там в readme.md были конфликт)

**Comment by HaCk3Dq** [comment]
This branch has conflicts that must be resolved.
Use the command line to resolve conflicts before continuing.
We can’t automatically merge this pull request.

**Comment by defoltbmd** [comment]
@HaCk3Dq должно перестать ругаться

**Pull request merged**
